"""
FastAPI app entrypoint.

Run with:
    uvicorn main:app --reload

Then visit http://127.0.0.1:8000/docs for interactive API docs (auto-generated by FastAPI) -
useful for testing endpoints before the frontend is ready.
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from database import engine, Base
from routes import jobs, candidates

# Creates tables if they don't exist yet (based on models.py)
Base.metadata.create_all(bind=engine)

app = FastAPI(title="AI Resume Screener API")

# Allow the React dev server (usually localhost:5173 for Vite) to call this API
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173", "http://localhost:3000"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(jobs.router)
app.include_router(candidates.router)


@app.get("/")
def root():
    return {"message": "AI Resume Screener API is running"}